### ISSUE TITLE
`ReferenceError: apos is not defined` when saving schema widget with joins

### ISSUE THREAD

**Issue by mcrider** [punkave/apostrophe-schemas#6]
I have a schema widget that looks like this:

```
   {
          name: 'conditionalSpeakers',
          label: 'Conditional Related Speakers',
          instructions: 'Enter the number of speakers to show',
          schema: [
            {
              name: 'relatedSpeakers',
              type: 'array',
              schema: [
                {
                  name: '_topic',
                  type: 'joinByOne',
                  withType: 'topic',
                  idField: 'topicId',
                  label: 'Topic',
                  limitText: '',
                  required: false
                },
                {
                  name: '_speaker',
                  type: 'joinByOne',
                  withType: 'speaker',
                  idField: 'speakerId',
                  label: 'Speaker',
                  limitText: '',
                  required: true
                },
                {
                  name: 'description',
                  type: 'string',
                  label: 'Description',
                  required: true
                }
              ]
            }
          ]
        }
```

When I try to save an entry I get this error:

```
ReferenceError: apos is not defined
    at getter (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe-schemas/index.js:933:18)
    at /path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe/lib/joinr.js:113:14
    at module.exports.byOne (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe/node_modules/joinr/index.js:39:14)
    at method (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe/lib/joinr.js:102:16)
    at Apos.self.join (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe/lib/joinr.js:105:12)
    at Apos.self.joinByOne (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe/lib/joinr.js:25:17)
    at Object.ApostropheSchemas.self.joinrs.joinByOne (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe-schemas/index.js:752:25)
    at /path/to/apostrophesite/node_modules/apostrophe-site/node_modules/apostrophe-schemas/index.js:956:36
    at iterate (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/path/to/apostrophesite/node_modules/apostrophe-site/node_modules/async/lib/async.js:165:9)
```

I modified apostrophe-schemas/index.js:933 from returning `apos.get` to `self._apos.get` and it worked fine.

**Comment by boutell** [comment]
Fixed, thanks. You're joining with a type that is neither a page in the "page types" menu nor a subclass of snippet, which is fine. But since we do it so rarely we missed it.
